version: "3.8"

services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - env.prod
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=car_park_prod
      - PHX_HOST=localhost
      - PHX_SERVER=true
      - MIX_ENV=prod
      # Override defaults if needed
      - SECRET_KEY_BASE=SOj3g1tjJ2vs4binBYVzpHbkUIBbUqs8X4c/3kn4z9tNiutrAgOlJglqBRjsgfGA
      - CAR_PARK_API_URL=https://api.data.gov.sg/v1/transport/carpark-availability
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/app/data:ro
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:4000/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=car_park_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d car_park_prod"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
